apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# qa environment. Tags are rewritten by Kargo when Freight is promoted from dev.
namespace: qa

resources:
  - ../../base

images:
  - name: ghcr.io/jmgilman/backend
    newTag: "0.4.0"
  - name: ghcr.io/jmgilman/frontend
    newTag: "0.2.0"
